import React from "react";
// 1. Đồng bộ Type: Sử dụng CvLayoutData từ file types/cv.ts đã thống nhất
import { CvLayoutData } from "../../../types/cv";

// 2. Sửa đường dẫn Blocks: Đảm bảo nhảy đúng từ templates -> editor -> components -> features
import { HeaderBlock } from "../../../features/cv-editor/components/HeaderBlock";
import { ExperienceBlock } from "../../../features/cv-editor/components/ExperienceBlock";
import { EducationBlock } from "../../../features/cv-editor/components/EducationBlock";
import { ProjectsBlock } from "../../../features/cv-editor/components/ProjectsBlock";
import { SkillsBlock } from "../../../features/cv-editor/components/SkillsBlock";

interface HarvardTemplateProps {
  data: CvLayoutData;
  isPreview?: boolean;
}

export const HarvardTemplate: React.FC<HarvardTemplateProps> = ({
  data,
  isPreview = false,
}) => {
  // Kiểm tra an toàn: Nếu không có data hoặc sections thì không render để tránh crash
  if (!data || !data.sections) return null;

  const { personalInfo, sections, theme } = data;

  // Harvard chuẩn thường dùng màu đen/xám đậm, ưu tiên primaryColor từ theme nếu có
  const primaryColor = theme.primaryColor || "#000000";

  // Hàm helper tìm section theo ID một cách an toàn
  const getSection = (id: string) => sections.find((s) => s.id === id);

  return (
    <div
      className="bg-white min-h-[297mm] w-full shadow-2xl px-16 py-12 m-0 print:shadow-none transition-all duration-500 text-slate-900"
      style={{
        fontFamily: theme.fontFamily || "serif",
        fontSize: theme.fontSize || "14px",
      }}
    >
      {/* 1. HEADER SECTION */}
      <HeaderBlock
        personalInfo={personalInfo}
        theme={theme}
        isPreview={isPreview}
        primaryColor={primaryColor}
        templateId="harvard-01"
      />

      <div className="space-y-6 mt-6">
        {/* 2. EDUCATION - Thường ưu tiên lên đầu trong mẫu Harvard */}
        {getSection("section-edu")?.visible && (
          <section className="break-inside-avoid">
            <h2 className="text-[13px] font-bold uppercase tracking-widest border-b border-slate-900 mb-2 pb-0.5">
              Education
            </h2>
            <EducationBlock
              section={getSection("section-edu")!}
              primaryColor={primaryColor}
              templateId="harvard-01"
            />
          </section>
        )}

        {/* 3. EXPERIENCE */}
        {getSection("section-exp")?.visible && (
          <section className="break-inside-avoid">
            <h2 className="text-[13px] font-bold uppercase tracking-widest border-b border-slate-900 mb-2 pb-0.5">
              Experience
            </h2>
            <ExperienceBlock
              section={getSection("section-exp")!}
              primaryColor={primaryColor}
              templateId="harvard-01"
            />
          </section>
        )}

        {/* 4. PROJECTS */}
        {getSection("section-projects")?.visible && (
          <section className="break-inside-avoid">
            <h2 className="text-[13px] font-bold uppercase tracking-widest border-b border-slate-900 mb-2 pb-0.5">
              Projects
            </h2>
            <ProjectsBlock
              section={getSection("section-projects")!}
              primaryColor={primaryColor}
              templateId="harvard-01"
            />
          </section>
        )}

        {/* 5. SKILLS */}
        {getSection("section-skills")?.visible && (
          <section className="break-inside-avoid">
            <h2 className="text-[13px] font-bold uppercase tracking-widest border-b border-slate-900 mb-2 pb-0.5">
              Skills & Others
            </h2>
            <SkillsBlock
              section={getSection("section-skills")!}
              isPreview={isPreview}
              primaryColor={primaryColor}
              templateId="harvard-01"
            />
          </section>
        )}
      </div>

      {/* FOOTER: Chỉ hiện khi in ấn */}
      <footer className="mt-12 text-center text-[10px] text-slate-400 hidden print:block">
        Generated by Career Compass AI
      </footer>
    </div>
  );
};

export default HarvardTemplate;
