// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ghgqxmhyguzlulxmustr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdoZ3F4bWh5Z3V6bHVseG11c3RyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQwNzAzMDMsImV4cCI6MjA4OTY0NjMwM30.Ovj6djoPBs5Pr-SxSNyo2Wz4snFsIMEy7lXK6Cy0B9I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});